import { cssr } from 'dsh-tauri-ui/client'
import { MOBILE_SETTINGS_MEDIA } from '../constants'

const { c } = cssr
const panel = '[data-dsh-mobile-settings][data-dsh-mobile-settings-view]'
const menu = `${panel}[data-dsh-mobile-settings-view="menu"]`
const detail = `${panel}[data-dsh-mobile-settings-view="detail"]`

export default c(`@media ${MOBILE_SETTINGS_MEDIA}`, [
  c(`html[data-dsh-mobile-sidebar] [data-slot="root"] > * > :has(> [data-slot="sidebar"] ${panel})`, {
    zIndex: 'auto',
  }),
  c(`[data-dsh-mobile-settings-overlay]:has(> ${panel})`, {
    position: 'fixed',
    inset: '0',
    width: '100vw',
    height: '100dvh',
    padding: '0',
    alignItems: 'stretch',
    justifyContent: 'stretch',
  }),
  c(panel, {
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    boxSizing: 'border-box',
    width: '100vw',
    maxWidth: 'none',
    height: '100dvh',
    maxHeight: '100dvh',
    minWidth: '0',
    minHeight: '0',
    margin: '0',
    padding: 'var(--dsh-mobile-safe-area-inset-top, env(safe-area-inset-top, 0px)) var(--dsh-mobile-safe-area-inset-right, env(safe-area-inset-right, 0px)) var(--dsh-mobile-safe-area-inset-bottom, env(safe-area-inset-bottom, 0px)) var(--dsh-mobile-safe-area-inset-left, env(safe-area-inset-left, 0px))',
    gap: '0',
    border: '0',
    borderRadius: '0',
    boxShadow: 'none',
    color: 'var(--dsw-alias-label-primary)',
    colorScheme: 'light',
    backgroundColor: 'Canvas',
    backgroundImage: 'linear-gradient(var(--dsw-alias-bg-layer-2, Canvas), var(--dsw-alias-bg-layer-2, Canvas))',
    overflow: 'hidden',
  }),
  c(`body[data-ds-dark-theme] ${panel}`, {
    colorScheme: 'dark',
  }),
  c(`${panel} [data-dsh-mobile-settings-nav]`, {
    display: 'flex',
    flexDirection: 'column',
    flex: '1 1 0',
    boxSizing: 'border-box',
    width: '100%',
    minWidth: '0',
    minHeight: '0',
    padding: '0 12px',
    gap: '8px',
  }),
  c(`${panel} [data-dsh-mobile-settings-title]`, {
    display: 'flex',
    alignItems: 'center',
    flex: '0 0 auto',
    boxSizing: 'border-box',
    minHeight: '52px',
    minWidth: '0',
    margin: '0',
    padding: '0 52px 0 12px',
    fontSize: '18px',
    fontWeight: '600',
    lineHeight: '24px',
    color: 'var(--dsw-alias-label-primary)',
  }),
  c(`${panel} [data-dsh-mobile-settings-list]`, {
    display: 'flex',
    flexDirection: 'column',
    boxSizing: 'border-box',
    flex: '1 1 0',
    height: '0 !important',
    minWidth: '0',
    minHeight: '0',
    width: '100%',
    padding: '0 0 12px',
    margin: '0',
    gap: '4px',
    overflowX: 'hidden',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
  }),
  c(`${panel} [data-dsh-mobile-settings-list] > button`, {
    flex: '0 0 auto',
    width: '100%',
    minWidth: '0',
    minHeight: '52px',
    height: 'auto',
    padding: '12px',
    gap: '12px',
    fontSize: '15px',
    lineHeight: '22px',
    textAlign: 'start',
    touchAction: 'manipulation',
  }),
  c(`${panel} [data-dsh-mobile-settings-list] > button > span`, {
    minWidth: '0',
    whiteSpace: 'normal',
    overflowWrap: 'anywhere',
  }),
  c(`${panel} [data-dsh-mobile-settings-content]`, {
    display: 'flex',
    flexDirection: 'column',
    flex: '1 1 0',
    position: 'static',
    boxSizing: 'border-box',
    width: '100%',
    minWidth: '0',
    minHeight: '0',
    padding: '0',
    gap: '0',
    border: '0',
  }),
  c(`${panel} [data-dsh-mobile-settings-header]`, {
    display: 'flex',
    flex: '0 0 auto',
    position: 'static',
    boxSizing: 'border-box',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '100%',
    minWidth: '0',
    height: 'auto',
    minHeight: '52px',
    padding: '52px 12px 0',
    gap: '0',
  }),
  c(`${panel} [data-dsh-mobile-settings-actions]`, {
    display: 'flex',
    flexWrap: 'wrap',
    position: 'static',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '100%',
    minWidth: '0',
    gap: '8px',
  }),
  c(`${panel} [data-dsh-mobile-settings-close]`, {
    position: 'absolute',
    top: 'calc(6px + var(--dsh-mobile-safe-area-inset-top, env(safe-area-inset-top, 0px)))',
    right: 'calc(12px + var(--dsh-mobile-safe-area-inset-right, env(safe-area-inset-right, 0px)))',
    zIndex: '2',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '40px',
    height: '40px',
    minWidth: '40px',
    minHeight: '40px',
    padding: '0',
    margin: '0',
    touchAction: 'manipulation',
  }),
  c(`${panel} [data-dsh-mobile-settings-controls]`, {
    position: 'absolute',
    top: 'var(--dsh-mobile-safe-area-inset-top, env(safe-area-inset-top, 0px))',
    left: 'calc(12px + var(--dsh-mobile-safe-area-inset-left, env(safe-area-inset-left, 0px)))',
    right: 'calc(64px + var(--dsh-mobile-safe-area-inset-right, env(safe-area-inset-right, 0px)))',
    zIndex: '1',
    display: 'grid',
    gridTemplateColumns: '40px minmax(0, 1fr)',
    alignItems: 'center',
    height: '52px',
    minWidth: '0',
    gap: '8px',
  }),
  c(`${panel} [data-dsh-mobile-settings-back]`, {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '40px',
    height: '40px',
    minWidth: '40px',
    padding: '0',
    touchAction: 'manipulation',
  }),
  c(`${panel} [data-dsh-mobile-settings-section-title]`, {
    minWidth: '0',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '16px',
    fontWeight: '500',
    lineHeight: '24px',
    color: 'var(--dsw-alias-label-primary)',
  }),
  c(`${panel} [data-dsh-mobile-settings-back]:focus-visible, ${panel} [data-dsh-mobile-settings-close]:focus-visible`, {
    outline: 'var(--dsw-focus-ring-width, 2px) solid var(--dsw-focus-ring-color, var(--dsw-alias-state-business-primary))',
    outlineOffset: '2px',
  }),
  c(`${panel} [data-dsh-mobile-settings-options]`, {
    boxSizing: 'border-box',
    flex: '1 1 0',
    height: '0 !important',
    width: '100%',
    minWidth: '0',
    minHeight: '0',
    padding: '12px 16px 24px',
    overflowX: 'auto',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
  }),
  c(`${menu} [data-dsh-mobile-settings-content]`, {
    flex: '0 0 auto',
  }),
  c(`${menu} [data-dsh-mobile-settings-header]`, {
    minHeight: '0',
    padding: '0 12px 12px',
  }),
  c(`${detail} [data-dsh-mobile-settings-nav]`, {
    position: 'absolute',
    inset: '0 auto auto 0',
    flex: 'none',
    width: '0',
    height: '0',
    padding: '0',
    gap: '0',
  }),
  c(`${detail} [data-dsh-mobile-settings-title]`, {
    position: 'absolute',
    width: '1px',
    height: '1px',
    minHeight: '0',
    padding: '0',
    margin: '-1px',
    overflow: 'hidden',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap',
  }),
  c(`${panel} [data-dsh-mobile-settings-list][hidden], ${panel} [data-dsh-mobile-settings-options][hidden], ${panel} [data-dsh-mobile-settings-controls][hidden]`, {
    display: 'none !important',
  }),
])
